import discord
from redbot.core import commands, Config
from random import randint

BaseCog = getattr(commands, "Cog", object)


class ConversationGames(BaseCog):
    """Conversation games"""

    def __init__(self):
        self.config = Config.get_conf(self, identifier=763123)
        default_global = {
            "wyr": [
                "...always be 10 minutes late or always be 20 minutes early?",
                "...lose all of your money and valuables or all of the pictures you have ever taken?",
                "...be able to see 10 minutes into your own future or 10 minutes into the future of anyone but yourself?",
                "...be famous when you are alive and forgotten when you die or unknown when you are alive but famous after you die?",
                "...go to jail for 4 years for something you didn’t do or get away with something horrible you did but always live in fear of being caught?",
                "...accidentally be responsible for the death of a child or accidentally be responsible for the deaths of three adults?",
                "...your shirts be always two sizes too big or one size too small?",
                "...live in the wilderness far from civilization or live on the streets of a city as a homeless person?",
                "...the general public think you are a horrible person but your family be very proud of you or your family think you are a horrible person but the general public be very proud of you?",
                "...live your entire life in a virtual reality where all your wishes are granted or in the real world?",
                "...be alone for the rest of your life or always be surrounded by annoying people?",
                "...never use social media sites / apps again or never watch another movie or TV show?",
                "...have an easy job working for someone else or work for yourself but work incredibly hard?",
                "...be the first person to explore a planet or be the inventor of a drug that cures a deadly disease?",
                "...have a horrible short term memory or a horrible long term memory?",
                "...be completely invisible for one day or be able to fly for one day?",
                "...be locked in a room that is constantly dark for a week or a room that is constantly bright for a week?",
                "...be poor but help people or become incredibly rich by hurting people?",
                "...live without the internet or live without AC and heating?",
                "...have a horrible job, but be able to retire comfortably in 10 years or have your dream job, but have to work until the day you die?",
                "...find your true love or a suitcase with five million dollars inside?",
                "...be able to teleport anywhere or be able to read minds?",
                "...die in 20 years with no regrets or die in 50 years with many regrets?",
                "...be feared by all or loved by all?",
                "...be transported permanently 500 years into the future or 500 years into the past?",
                "...never be able to use a touchscreen or never be able to use a keyboard and mouse?",
                "...be able to control fire or water?",
                "...have everything you eat be too salty or not salty enough no matter how much salt you add?",
                "...have hands that keep  growing as you get older or feet that keep growing as you get older?",
                "...be unable to use search engines or unable to use social media?",
                "...give up bathing for a month or give up the internet for a month?",
                "...donate your body to science or donate your organs to people who need them?",
                "...go back to age 5 with everything you know now or know now everything your future self will learn?",
                "...relive the same day for 365 days or lose a year of your life?",
                "...have a golden voice or a silver tongue?",
                "...be able to control animals (but not humans) with your mind or control electronics with your mind?",
                "...sell all of your possessions or sell one of your organs?",
                "...lose all of your memories from birth to now or lose your ability to make new long term memories?",
                "...be infamous in history books or be forgotten after your death?",
                "...never have to work again or never have to sleep again (without suffering negative health effects)?",
                "...be gorgeous but stupid or intelligent but ugly?",
                "...get one free round trip international plane ticket every year or be able to fly domestic anytime for free?",
                "...be balding but fit or overweight with a full head of hair?",
                "...be able to be free from junk mail or free from email spam for the rest of your life?",
                "...be fluent in all languages and never be able to travel or be able to travel anywhere for a year but never be able to learn a word of a different language?",
                "...have an unlimited international first class ticket or never have to pay for food at restaurants?",
                "...see behind every closed door or guess the combination of every safe on the first try?",
                "...live in virtual reality where you are all powerful or live in the real world and be able to go anywhere but not be able to interact with anyone or anything?",
                "...never be able to eat meat or never be able to eat vegetables?",
                "...give up watching videos for a year or give up playing games for a year?",
                "...always be able to see 5 minutes into the future or always be able to see 100 years into the future?",
                "...super sensitive taste or super sensitive hearing?",
                "...be a practicing doctor or a medical researcher?",
                "...be married to a 10 with a bad personality or a 6 with an amazing personality?",
                "...never be able to drink sodas like coke again or only be able to drink sodas and nothing else?",
                "...be a reverse centaur or a reverse mermaid/merman?",
                "...have constantly dry eyes or a constant runny nose?",
                "...be a famous director or a famous actor?",
                "...not be able to open any closed doors (locked or unlocked) or not be able to close any open doors?",
                "...give up all drinks except water or give up eating anything that was cooked in an oven?",
                "...have to speak every word you read or sing everything you say out loud?",
                "...have what you are thinking appear above your head for everyone to see or have absolutely everything you do live streamed for anyone to see?",
                "...be put in prison with the hardest of the hardened criminals for one year or be put in a relatively relaxed prison where wall street types are held for ten years?",
                "...have a clown only you can see that follows you everywhere and just stands silently in a corner watching you without doing or saying anything or have a real life stalker who dresses like the Easter bunny that everyone can see?",
                "...kill one innocent person or five people who committed minor crimes?",
                "...have a completely automated home or a self-driving car?",
                "...work very hard at a rewarding job or hardly have to work at a job that isn’t rewarding?",
                "...be held in high regard by your parents or your friends?",
                "...be an amazing painter or a brilliant mathematician?",
                "...be reincarnated as a fly or just cease to exist after you die?",
                "...be able to go to any theme park in the world for free for the rest of your life or eat for free at any drive through restaurant for the rest of your life?",
                "...be only able to watch the few movies with a rotten tomatoes score of 95-100% or only be able to watch the majority of movies with a rotten tomatoes score of 94% and lower?",
                "...never lose your phone again or never lose your keys again?",
                "...have one real get out of jail free card or a key that opens any door?",
                "...have a criminal justice system that actually works and is fair or a government that is free of corruption?",
                "...have real political power but be relatively poor or be ridiculously rich and have no political power?",
                "...have the power to gently nudge anyone’s decisions or have complete control of five people?",
                "...have everyone laugh at your jokes but not find anyone else’s jokes funny or have no one laugh at your jokes but you still find other people’s jokes funny?",
                "...be the absolute best at something that no one takes seriously or be well above average but not anywhere near the best at something well respected?",
                "...lose the ability to read or lose the ability to speak?",
                "...live under a sky with no stars or live under a sky with no clouds?",
                "...humans go to the moon again or go to mars?",
                "...never get angry or never be envious?",
                "...have free Wi-Fi wherever you go or be able to drink unlimited free coffee at any coffee shop?",
                "...be compelled to high five everyone you meet or be compelled to give wedgies to anyone in a green shirt?",
                "...live in a house with see-through walls in a city or in the same see-though house but in the middle of a forest far from civilization?",
                "...take amazing selfies but all of your other pictures are horrible or take breathtaking photographs of anything but yourself?",
                "...use a push lawn mower with a bar that is far too high or far too low?",
                "...be able to dodge anything or be able ask any three questions and have them answered accurately?",
				"...be covered in fur or covered in scales?", 
				"...know the history of every object you touched or be able to talk to animals?",
				"...have all traffic lights you approach be green or never have to stand in line again?",
				"...spend the rest of your life with a sailboat as your home or an RV as your home?",
				"...be the first person to explore a planet or be the inventor of a drug that cures a deadly disease?",
				"...5% of the population have telepathy, or 5% of the population have telekinesis? (You're not part of either group.)",
				"...move to a new city or town every week or never be able to leave the city or town you were born in?",
				"...travel the world for a year on a shoestring budget or stay in only one country for a year but live in luxury?",
				"...suddenly be elected a senator or suddenly become a CEO of a major company?",
				"...know how above or below average you are at everything or know how above or below average people are at one skill/talent just by looking at them?",
				"...every shirt you ever wear be kind of itchy or only be able to use 1 ply toilet paper?",
				"...wear a wedding dress/tuxedo every single day or wear a bathing suit every single day?",
				"...have skin that changes color based on your emotions or tattoos appear all over your body depicting what you did yesterday?",
				"...become twice as strong when both of your fingers are stuck in your ears or crawl twice as fast as you can run?",
				"...thirty butterflies instantly appear from nowhere every time you sneeze or one very angry squirrel appear from nowhere every time you cough?",
				"...be forced to eat only spicy food or only overly salty food?",
				"...have a rewind button or a pause button on your life?",
				"...win the lottery or live twice as long?",
				"...work more hours per day, but fewer days or work fewer hours per day, but more days?",
				"...be Batman or Spiderman?",
				"...be the most popular person in your circle or the smartest?",
				"...have a cook or a maid?",
				"...have a 10-hour dinner with a headstrong politician from an opposing party, or attend a 10-hour concert for a music group you detest?",
				"...hear the good news or the bad news first?",
				"...be your own boss or work for someone else?",
				"...have nosy neighbors or noisy neighbors?",
				"...have your flight delayed by 8 hours or lose your luggage?",
				"...babysit a crying infant for a day or have an unwanted houseguest for a week?",
				"...have a dog with a cat’s personality or a cat with a dog’s personality?",
				"...look 10 years older from the neck up, or the neck down?",
				"...read the book or watch the movie?",
				"...have to dress all in bright orange or all in lime green for the rest of your life?",
				"...have every movie spoiled for you before you watch it or not be able to watch a new movie until it’s been out for a year?",
				"...live in the middle of nowhere, with no people or stores within a 10 mile radius, or live in a busy city?",
				"...have you browser history made public or the last 20 pictures in your camera roll made public?",
				"...change the outcome of the last election or get to decide the outcome of the next election?",
				"...wear your grandpa’s clothes or have your grandpa’s hair?",
				"...eat your hair trimmings after every haircut or eat your nail clippings each time you cut your nails?",
				"...have your phone hacked and all your info leaked or have your house burgled?",
				"...get a really bad tattoo or have to wear black contacts to every job interview?",
				"...eat a cup of lawn clippings or a cup of dirt?",
				"...have venomous fangs or a second set of eyes in the back of your head?",
				"...receive several small but meaningful gift from your significant other receive one big, flashy gift?",
				"...blindly pick out your outfit each morning or have your mom pick out your clothes?",
				"...sleep in the same clothes you wore during the day or sleep without any pillows or blankets?",
				"...be the opposite gender for one day or be any animal for one day?",
				"...be able to taste colors or see smells?",
				"... wear the same pair of socks for a month or wear the same pair of underwear for a week?",
				
            ],
            "nhie": [
                "...dressed as the opposite sex.",
                "...watched Spongebob Squarepants.",
                "...cried during a Pixar movie.",
                "...'cleaned up' by piling everything into a closet.",
                "...sung karaoke.",
                "...watched the 'Gangnam Style' music video.",
                "...had a crush on someone from 'Full House'.",
                "...pretended to know a stranger.",
                "...worn sleepwear and pretended it was clothing.",
                "...said 'excuse me' when there was no one around.",
                "...scared myself in a mirror.",
                "...missed a high five.",
                "...heard someone else doing it.",
                "...sang in the shower.",
                "...blamed farts on an animal.",
                "...secretly wished I were a wizard at Hogwarts.",
                "...slept in regular clothing.",
                "...had a nightmare about zombies chasing me.",
                "...pretended to laugh at a joke I didn't get.",
                "...been scared of clowns.",
                "...thought a cartoon character was hot.",
                "...faked being sick so I could play video games.",
                "...tried out to be an extra in a movie.",
                "...scored over 100 while bowling.",
                "...used an Instant Pot.",
                "...made a duck face when taking a selfie.",
                "...looked out the car's passenger seat window and imagined it was a scene from a music video.",
                "...actually laughed out loud when typing 'lol'.",
                "...reread an email immediately after sending it.",
                "...daydreamed about being on a talk show and what I'd talk about.",
                "...googled my own name to see what comes up.",
                "...pretended I was running from zombies while on a run.",
                "...sat in the shower.",
                "...ugly cried for no reason.",
                "...creeped on someone I just met on social media.",
                "...thought about how a loved one could identify me if my face was horribly disfigured in an accident.",
                "...answered someone 'left' or 'right' without thinking, because I have a 50/50 chance of being right.",
                "...been out of the country.",
                "...flown in a helicopter.",
                "...been on stage in front of a crowd.",
                "...lied in a job interview.",
                "...stalked a crush.",
                "...sung karaoke.",
                "...thought about what type of dog I would be.",
                "...watched children's cartoons I'm too old for.",
                "...lost sunglasses that I was already wearing.",
                "...locked my keys in my car.",
                "...not tipped at a restaurant.",
                "...given money to a homeless person.",
                "...tried to look at the sun.",
                "...bungee-jumped.",
                "...had surgery.",
                "...jumped out of a plane.",
                "...made a wish at a fountain.",
                "...accidentally eaten a bug.",
                "...cut someone in line.",
                "...stayed up all night.",
                "...read a single Harry Potter book.",
                "...been inside of a library.",
                "...lied about my age.",
                "...shot a gun.",
                "...had a cavity.",
                "...been mini golfing.",
                "...seen an elephant in real life.",
                "...been to Disney World.",
                "...bought clothing online.",
                "...had someone draw a caricature of me.",
                "...owned an Xbox.",
                "...spent hours watching funny videos on Youtube.",
                "...met a celebrity.",
                "...thought a movie was better than the book.",
                "...voted.",
                "...owned a watch.",
                "...ridden a skateboard.",
                "...learned how to play a musical instrument.",
                "...seen snow.",
                "...finished a Sudoku puzzle.",
                "...googled something so I'd know how to spell it.",
                "...cheated on a test.",
                "...cried watching Homeward Bound.",
                "...licked a frozen pole.",
                "...had gum in my hair.",
                "...taken a horrible picture on picture day.",
                "...been a bully.",
                "...wanted to be a superhero.",
                "...been scared of the dark.",
                "...had trouble sleeping after watching a scary movie.",
                "...stayed up all night.",
                "...been to a sleepover.",
                "...had a birthday party.",
                "...cried at school.",
                "...sang on a stage.",
                "...performed in a talent show.",
                "...killed ants with a magnifying glass.",
                "...dropped Mentos into Coke or Pepsi.",
                "...eaten something on a dare.",
                "...used the excuse 'my dog ate my homework'.",
                "...sucked my thumb.",
                "...believed my toys had feelings.",
                "...been terrified of a theme park ride.",
                "...been to a haunted house.",
                "...been sent to the principal's office.",
                "...done an Easter Egg Hunt.",
                "...built a fort with blankets.",
                "...fallen off a bike.",
                "...played video games all day.",
                "...stolen money from a sibling's piggy bank.",
                "...wished I had bunk beds.",
                "...played Pokemon.",
                "...been on a family road trip.",
                "...named a stuffed animal.",
                "...used training wheels.",
                "...eaten only candy for dinner.",
                "...written notes on the desk to use during a test.",
                "...tried to sign a permission slip for my parents.",
                "...stolen a friend's story and pretend it happened to me.",
                "...thrown something out of the school bus window.",
                "...lied about staying after school and went somewhere else.",
                "...hopped seats on the school bus.",
                "...accidentally sharted.",
                "...forgotten the punchline of a joke.",
                "...sang a song out loud and messed the lyrics.",
                "...walked in on someone in the bathroom.",
                "...had someone walk in on me in the bathroom.",
                "...sent a text to the wrong person.",
                "...tried to pass a silent fart, but it came out loud instead.",
                "...tripped in public.",
                "...wet the bed after childhood.",
                "...accidentally pooped my pants.",
                "...attempted martial arts moves while by myself.",
                "...drove over a curb.",
                "...mistaken a man for a women or vice versa.",
                "...laughed so hard, I peed my pants.",
                "...picked a wedgie in public.",
                "...called the wrong person, but pretended I meant to call them.",
                "...gone into the wrong restroom.",
                "...been so freaked to be outside at night, that I ran back in.",
                "...lost my swimwear bottoms.",
                "...had diarrhea at a friend's house.",
                "...broken a piece of furniture by sitting on it.",
                "...arrived somewhere late and had everyone staring at me.",
                "...had food stuck in my teeth all day.",
                "...walked around with my zipper down.",
                "...bought a children's toy for myself, as an adult.",
                "...recorded video of myself singing or dancing.",
                "...been caught picking my nose.",
                "...gotten something stuck in my nose.",
                "...greeted someone I thought was someone else.",
				"...been drunk.",
				"...had chicken pox.",
				"...had a lucid dream.",
				"...gotten or given a hickey.",
				"...had a wardrobe malfunction.",
				"...gotten stitches.",
				"...had food poisoning.",
				"...gone commando.", 
				"...broken a bone.",
            ],
            "truths": [
                "What was the last thing you searched for on your phone?",
                "If you had to choose between going naked or having your thoughts appear in thought bubbles above your head for everyone to read, which would you choose?",
                "After you've dropped a piece of food, what's the longest time you've left it on the ground before eating it?",
                "Have you ever played Cards Against Humanity with your parents?",
                "What's the first thing you would do if you woke up one day as the opposite sex?",
                "Have you ever peed in the pool?",
                "Who do you suspect is the worst dressed person here?",
                "Of the people here, who do you want to trade lives with?",
                "Did you have an imaginary friend growing up?",
                "Do you cover your eyes during a scary parts of a movie?",
                "Have you ever practiced kissing in a mirror?",
                "Did your parents ever give you the “birds and the bees” talk?",
                "What is your worst habit?",
                "Have you ever walked into a wall?",
                "Do you ever talk to yourself in the mirror?",
                "You’re in a public restroom and just went #2, then you realized your stall has no toilet paper. What do you do?",
                "What would be in your web history that you’d be embarrassed if someone saw?",
                "Do you sleep with a stuffed animal?",
                "Do you drool in your sleep?",
                "Do you talk in your sleep?",
                "Tell us about your crush (if you have one).",
                "What is your go-to song for the shower?",
                "How would you rate your looks on a scale of 1 to 10?",
                "What color underwear are you wearing right now?",
                "If you were rescuing family or friends from a burning building and you had to leave one person behind, who would it be?",
                "Do you ever try to solve the problems between your best friend and his/her crush?",
                "Have you ever tried to sing a tongue twister in a musical way?",
                "Tell us your weirdest habit.",
                "Do you like parties?",
                "Did you ever have a crush on any of your teachers?",
                "Do you go directly to your home after college in the evening?",
                "How many partners have you had?",
                "Suppose you were a billionaire, how would you spend your time?",
                "If your parents forced you to leave home, where would you go?",
                "If you wanted to start your own business, what it would be?",
                "Have you ever had the crush on someone much younger or older than you? What’s the biggest age difference?",
                "How many hours do you exercise a day?",
                "Have you ever farted in public and got caught?",
                "Who is the worst kisser you have ever kissed and why?",
                "What is your favorite villain character?",
                "When was the first time you fell in love and with whom?",
                "What has been the most embarrassing moment you've experienced so far?",
                "Tell us about your secret (non-sexual) fantasy.",
                "What turns you on the most?",
                "What is the most sensual piece of clothing you own?",
                "What do you find attractive in people?",
                "Have you ever gone skinny dipping?",
                "When was the first time you kissed someone? Who was it?",
                "Have you got a secret talent?",
                "What is the wildest thing you have ever done in your life so far?",
                "Do you prefer to have music in the background, or for it to be be quiet?",
                "Have you roleplayed?",
                "Have you ever cheated on any test?",
                "Who is the most annoying person you know?",
                "Have you ever lied to your parents about what you were doing after school?",
                "Have you ever blamed something that you have done on one of your siblings?",
                "What is your biggest pet peeve?",
                "What is the best vacation you’ve ever been on?",
                "Have you ever told one of your best friend’s secrets, even if you said you wouldn’t?",
                "Have you ever had a crush on someone that your best friend has dated?",
                "What is the most annoying thing that one of your siblings has done?",
                "What is your favorite thing about your job?",
                "What is the longest time you have ever been grounded?",
                "What is the longest time that you think you could go without your cell phone?",
                "What is the most expensive thing you own?",
                "If you had the choice to live on your own right now, would you do it?",
                "Would you ever get on a dating website?",
                "If you could own your own business one day, what would it be?",
                "What is your favourite kind of clothing?",
                "What celebrity are you obsessed with?",
                "What is the funniest youtube video you have ever seen?",
                "Who is the worst teacher you have ever had, why?",
                "What is your favourite sports team?",
                "What's the craziest thing that you have ever done without your parents knowing?",
                "What is your favourite song?",
                "Could you go two months without talking to your friends?",
                "Have you ever walked in on your parents or siblings doing it?",
                "Have you ever tasted a booger?",
                "What are some things you think about when sitting on the toilet?",
                "Do you cover your eyes during a scary part in a movie?",
                "What is your guilty pleasure?",
                "Has anyone ever walked in on you when taking a shit in the bathroom?",
                "Do you pick your nose?",
                "Do you sing in the shower?",
                "Have you ever peed yourself?",
                "What was your most embarrassing moment in public?",
                "Have you ever tried to take a sexy picture of yourself?",
                "What does your dream partner look like?",
                "What was the last thing you texted?",
                "Do you think you'll marry your current partner?",
                "How often do you wash your undergarments?",
                "Have you ever tasted ear wax?",
                "Have you ever tasted your sweat?",
                "What is the most illegal thing you have ever done?",
                "Who is your favourite parent?",
                "Would you trade in your dog for a million dollars?",
                "If you were allowed to marry more than one person, would you?",
                "Would you choose to save 100 people without anyone knowing about it or not save them but have everyone praise you for it?",
                "If you could only hear one song for the rest of your life, what would it be?",
                "If you lost one day of your life every time you said a swear word, would you try not to do it?",
                "Would you rather live with no internet or no A/C or heating?",
                "If someone offered you $1 million dollars to break up with your partner, would you do it?",
                "If you were reborn, what decade would you want to be born in?",
                "If you could go back in time in erase one thing you said or did, what would it be?",
                "If you could suddenly become invisible, what would you do?",
                "Have you ever been caught checking someone out?",
                "Have you ever waved at someone thinking they saw you when really they didn't? What did you do when you realized it?",
                "What's the longest time you've stayed in the bathroom, and why did you stay for that long?",
                "What's the most unflattering picture of you?",
                "Have you ever cried because you missed your family?",
                "Describe the strangest dream you've ever had. Did you like it?",
                "Have you ever posted something on social media that you regret?",
                "What is your biggest fear?",
                "Do you pee in the shower?",
                "The world ends next week and you can do anything you want. What would you do?",
                "Would you wear your shirt inside out for a whole day if someone paid you $100?",
                "What is the most childish thing that you still do?",
                "How far would you go to land the partner of your dreams?",
                "Have you ever kept a library book?",
                "What children’s movie could you watch over and over again?",
                "Do you have bad foot odor?",
                "Do you have any silly nicknames?",
                "How many pancakes have you eaten in a single sitting?",
                "Have you ever accidentally hit something with your car?",
                "Have you ever watched a movie you knew you shouldn’t?",
                "Have you ever wanted to try LARP (Live Action Role-Play)?",
                "What app on your phone do you waste the most time on?",
                "Have you ever pretended to be sick to get out of something? If so, what was it?",
                "What is the most food you’ve eaten in a single sitting?",
                "Do you dance when you’re by yourself?",
                "What song do you sing every time?",
                "Do you own a pair of footie pajamas?",
                "Are you scared of the dark?",
                "What ‘As seen on TV’ product do you secretly want to buy?",
                "Do you still take bubble baths?",
                "If you were home by yourself all day, what would you do?",
                "How many selfies do you take?",
                "What is something you’ve done to try to be ‘cooler’?",
                "When was the last time you brushed your teeth?",
                "Have you ever used self tanner?",
                "What does your favorite pajamas look like?",
                "Do you have a comfort object?",
                "Have you ever butt-dialed someone?",
                "Do you like hanging out with your parents?",
                "Have you ever got caught doing something you shouldn’t?",
                "What part of your body do you love and which part do you hate?",
                "Have you ever had lice?",
                "Do you lick your plate?",
                "Do you write in a diary?",
                "Who would you hate to see naked?",
                "How long have you gone without a shower?",
                "If you could only text one person for the rest of your life, but you could never talk to that person face to face, who would that be?",
                "How long have you gone without brushing your teeth?",
                "What's one thing you would never do on a first date?",
                "What have you seen that you wish you could unsee?",
                "If you could be reincarnated into anyone's body, who would you want to become?",
                "What's one food that you will never order at a restaurant?",
                "What's the worst weather to be stuck outside in if all you could wear was a bathing suit?",
                "If your car broke down in the middle of the road, who in this room would be the last person you would call? Why?",
                "What's the most useless piece of knowledge you know?",
                "What did you learn in school that you wish you could forget?",
                "Is it better to use shampoo as soap or soap as shampoo?",
                "If you ran out of toilet paper, what would you do?",
                "If you could only use one swear word for the rest of your life, which one would you choose?",
                "What's the best thing to say to your friend that would be the worst thing to say to your crush?",
                "Would you rather eat dog food or cat food?",
                "If you had nine lives, what would you do that you wouldn't do now?",
                "If you could play a prank on anyone without getting caught, who would you play it on?",
                "Have you ever pretended to like a gift? How did you pretend?",
                "If you could choose to never sweat for the rest of your life or never have to use the bathroom, which would you choose?",
                "If you could spend every waking moment with your partner, would you?",
                "What's your biggest pet peeve?",
                "Describe your perfect date.",
                "Would you ever date two people at once if you could?",
                "You have to delete every app on your except for five. Name the five you would keep.",
                "Have you ever sent a nude?",
                "Have you ever received a nude?",
                "Have you ever gotten mad at a friend for posting an unflattering picture of you?",
                "Have you ever sent someone the wrong text?",
                "What the biggest deal breaker for you?",
                "Have you ever regretted something you did to get a someone's attention?",
                "Would you ever be mean to someone if it meant you could save your close friend from embarrassment?",
                "Do you frequently stalk anyone on social media? Who?",
                "If you only had 24 hours to live and you could do anything with anyone in this room, who would it be and what would you do with that person?",
                "What's the most flirtatious thing you've ever done?",
                "Have you ever smoked?",
                "Have you ever tried drugs?",
                "What kind of alcohol do you like?",
                "What's the craziest thing you've done while under the influence?",
                "If you were trapped for three days on an island, who are three people in this room you would bring with you and why?",
                "Would you go to a nude beach?",
                "If you had to marry someone in this room, who would it be?",
                "Do you have hidden piercings or tattoos?",
                "How long was your longest relationship?",
                "Do you want to get married one day?",
                "Do you want to have kids? How many?",
                "Would you ever get into a long distance relationship?",
                "What was your first job?",
                "How many hours would you spend online if you didn't have obligations?",
                "How tall do you want to be?",
                "What are you most excited about?",
                "What's you dream job?",
                "What was a rumor that went around about you?",
                "Have you ever failed a class?",
                "Have you ever made out at school?",
                "Who did you hate sitting next to in class?",
                "What do you think is better: tests or essays?",
                "Have you ever gotten into a (fist) fight?",
                "What was the worst score you’ve ever gotten on a test?",
                "Have you ever fallen asleep in class?",
                "Have you ever gotten detention or been suspended?",
                "Who has seen you without clothes on, outside of family and partners?",
                "Have you ever been attracted to the same sex?",
                "Do you sleep in the nude?",
                "Would you wear your sexiest clothes for $100?",
				"What’s one thing you cannot live without?",
				"Describe the last dream you had",
				"What’s been your most physically painful experience?",
				"Boxers or briefs?",
				"What's the weirdest thing you've seen/experienced in public?",
				"What’s one thing in your life you wish you could change?",
				"What's the weirdest thing we'd find in your cabinets?",
				"What do you want on your tombstone?",
				"What’s your favorite possession?",
				"What’s the pettiest thing you’ve ever done?",
				"What's your biggest regret?",
				"What's the biggest misconception about you?",
				"What was the last thing you googled?",
				"If you were to paste right now, what would we see?",
				"What game did you not expect to like?",
				"What is your favorite form of entertainment?",
				"What game would you like to shill to literally everyone?",
				"Whose Youtube videos always get an immediate click from you?",
				"What is your gaming pet peeve?",
				"What is your preferred form of input for gaming? (Keyboard, any number of controllers...)",
				"What kind of keyboard do you have?",
				"Who was your first waifu/husbando, if any?",
				"What feature do you wish more games had?",
				"What game is overrated?",
				"What do you regret buying?",
				"Do you get compliments? What are they?",
				"Do pineapples belong on pizza?",
				"What's the most awkward situation you've been in?",
            ],
        }
        self.config.register_global(**default_global)

    @commands.command(aliases=["wyr"])
    @commands.bot_has_permissions(embed_links=True)
    async def wouldyourather(self, ctx):
        """Would you rather?"""

        strings = await self.config.wyr()
        mn = len(strings)
        i = randint(0, mn - 1)

        # Build Embed
        embed = discord.Embed()
        embed.title = "Would you rather.."
        embed.description = strings[i]
        await ctx.send(embed=embed)

    @commands.command(aliases=["nhie"])
    @commands.bot_has_permissions(embed_links=True)
    async def neverhaveiever(self, ctx):
        """Never have I"""

        strings = await self.config.nhie()
        mn = len(strings)
        i = randint(0, mn - 1)

        # Build Embed
        embed = discord.Embed()
        embed.title = "Never have I ever.."
        embed.description = strings[i]
        await ctx.send(embed=embed)
		
    @commands.command()
    @commands.bot_has_permissions(embed_links=True)
    async def truth(self, ctx):
        """Ask a truth question to users!"""

        strings = await self.config.truths()
        mn = len(strings)
        i = randint(0, mn - 1)

        # Build Embed
        embed = discord.Embed()
        embed.title = "Truth"
        embed.description = strings[i]
        await ctx.send(embed=embed)